# Common configuration.
AllCops:
  # Include gemspec and Rakefile
  Exclude:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
    - 'vendor/**/*'
    - 'test/test_helper_methods.rb'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
    
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
  
Style/RescueModifier:
  Exclude:
    - 'lib/core_ext/hash.rb'

Naming/FileName:
  Exclude:
    - 'lib/**/*'
    - 'test/**/*'